frameworkVersion: ">=1.2.1"

service: tensorflow-lambda-gan

provider:
  name: aws
  runtime: python2.7
  stage: dev
  region: us-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::vb-tf-aws-lambda-model"
        - "arn:aws:s3:::vb-tf-aws-lambda-model/*"
        - "arn:aws:s3:::vb-tf-aws-lambda-images"
        - "arn:aws:s3:::vb-tf-aws-lambda-images/*"

functions:
  predict:
    handler: handler.predict
    events:
      - http:
          path: /predict
          method: get